### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by Graveflo** [arnetheduck/nph#98]
```nim
x.add (func1 do: x)[0]
```

```
--- Input ---

x.add (func1 do: x)[0]

--- Formatted ---
x.add func1 do:
  x[0]

--- PRE ---
kind: "nkBracketExpr"
sons:
  - kind: "nkCall"
    sons:
      - kind: "nkIdent"
        ident: "func1"
      - kind: "nkStmtList"
        sons:
          - kind: "nkIdent"
            ident: "x"
  - kind: "nkIntLit"
    intVal: 0
--- POST ---
kind: "nkCall"
sons:
  - kind: "nkIdent"
    ident: "func1"
  - kind: "nkStmtList"
    sons:
      - kind: "nkBracketExpr"
        sons:
          - kind: "nkIdent"
            ident: "x"
          - kind: "nkIntLit"
            intVal: 0
```
